# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3612b44cecedc42b4d156f25d2ca01a64e9759ab4c9cda978190de4aeb5dd4e42ff06de5908e97e302b76c35f28a7bab900e25f419df164b8164ba32d1c2987f

test:
  secret_key_base: c287b06c54cf1fe53658281576b8c49ba707a2233cf6782e4889b2937af17f566fc6ded70651f00a9a4aae5233a8c29fde147bd7b746f4ae40fd7eb411c52ea2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
